### ISSUE TITLE
Meraki dashboard shows Bad request since upgrade to node v 16.16.0

### ISSUE THREAD

**Issue by rookie50** [MiGoller/ioBroker.merakicmx#30]
**Describe the bug**  
Message from Dashboard:
Failed to validate with status code: 400, error message:
Bad Request

**Versions:**  
 - Adapter version: 0.2.7
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0
 - Operating system: Linux Debian Bullseye with Docker 20.10.17 running latest buanet iobroker

**Additional context**  
The validator string matches in dashboard and adapter setting and is reachable from outsite via a revers proxy. Another system works correctly with JS controller 4.0.23 and node 14.20.0. So I expect an incomatible node version. Is it possble to get the adapter working on Node version 16? Additional to this I get a lot of log entries in Node 14.20.0:

Read-only state "merakicmx.0.info.connection" has been written without ack-flag with value "true"

Kind regards
Rookie50

**Comment by MiGoller** [comment]
Hey @rookie50 , looks like I'll have to check and probably rewrite the adapter for Node.js 16x. Please be patient.

**Comment by rookie50** [comment]
hey @MiGoller, thank you for taking care of it!! Take your time ;-)

**Comment by MiGoller** [comment]
The adapter ist working again on my development instance on Node.js v16.16.0 and JS-Controller version v4.0.23.

The Meraki dashboards shows a `400 Bad request` error, right? Please verify your receiver setup in the Dashboard regarding using API version 2. Meraki has published a v3.1 API but the adapter requires v2.

**Comment by rookie50** [comment]
I have checked all settings and copied again the validator and secret to the adapter. The selected API version is v2. Then I verified the reachablitiy from outsite and get the correct validator string back from your iobroker adapter. So my revers proxy is correct as well.  
The reciever work with http at port 1890 and my site is reachable with https and a vaild Letsencrypt certificate.

**Comment by MiGoller** [comment]
Ok. Not sure about that, but in the past the receiver had to accessible on port 80 `http` as well for querying the validator id. But if your setup has worked on Node.js v14.x ... don't modify that! A new version is on the way.

**Comment by MiGoller** [comment]
Hey @rookie50 , please give the new v0.2.8 a try. Execute the following command in the iobroker root directory (e.g. in `/opt/iobroker`):

``` shell
npm install iobroker.merakicmx
```

Please do not install or update the adapter from a GitHub URL; due to a bug in `npm` the installation or update process would take about 10 min. or even more.

Good luck and let me know if it works, please.

KR,
MiGoller

**Comment by rookie50** [comment]
Hi,

looks like a ssl certificate problem. In a packet capture I see that the dashboard report it back to the adapter. I use a wildcard certificate. It seems that Meraki will not accept it anymore. I will raise a support case and ask them.

Kind regards

Robert

**Comment by MiGoller** [comment]
Ok, I'll wait for your feedback before I'll close this issue.

BTW: Probably your reverse proxy will be able to receive LE certificates for dedicated hostnames. I had a similar issue with another service running behind a Traefik edge router. Had to switch from DNS challenge to http challenge to get it up and running.

**Comment by MiGoller** [comment]
Did you upgrade to my new release? There should be less warnings than in the past.

**Comment by rookie50** [comment]
Hi, yes I have updated to the new release. And the case ist resolved now. The Meraki Support advised me to use the fullchain.pem instead of the cert.pem. Now it is working.
Thank you for your help here.
I don't have enough time to check the logging regarding the warning. But I believe you ;-)

**Comment by rookie50** [comment]
Resolved
