### ISSUE TITLE
Verify the connection to Meraki API

### ISSUE THREAD

**Issue by rookie50** [MiGoller/ioBroker.merakicmx#4]
Hi Mi,

at first great work at this adapter!!! I want to use it as a part of presence detection. But I see a hopefully little problem. Is it possible to add detection that the adapter get answer from the meraki cloud API at the choosen port, e.g 1890? I want to prevent to get a wrong statement (not at home) when something is not working and use a differnet adapter with local resources.

Kind regards

**Comment by MiGoller** [comment]
Hey Rookie50,

thank you very much for your feedback. Well, lets see if I get you right.

You're looking for a kind of indicator if your adapter instance is receiving messages from the Meraki API, right? I think of at least two possibilities to get this request working.

1. I'll check if the the adapter receives messages from the Meraki API every 2 up to 3 minutes. That's the period of time Meraki will push messages to your adapter. I do not have any chance to change that behavior, but I'll talk to my Meraki contacts next time I'll see them.

2. I could try to make a REST-call to the Meraki API to get the status from Meraki's point of view, e.g. if Meraki is able to pass any messages to your adapter instance.

Anyway I'd create an indicator data point to show the adapter's status.

Is it this you are looking for?

BTW: I use the adapter as a part of presence detection system as well. Energy saving settings do have an impact on the detection of mobile phones. Do you have an Bluetooth enabled AP? I check for BLE devices as well and the detection is good and stable.


Kind regards,
Michael

**Comment by rookie50** [comment]
Hi Michael,

yes, you see it right. The connected indicator at the objects is not reporting that your adapter gets data from the Meraki cloud. I'm using a revers proxy in front of my ioBroker. And e.g. when I stop the forwarding to the proxy all devices reported by cmx are down, but the status of the adapter is still up.
BTW, the Meraki system means that the adapter at my end is not connected. But I'm getting status updates. It seems that the way back is not working correctly. I haven't the time to check the communication way. When I have reviewed it I will let you know.

FYI: yes I using a MR32 and a MR33. What kind of BLE device you are using? I still test with "Tile". And I see that this is working.

KR,

Robert

**Comment by MiGoller** [comment]
Hi Robert,

ok. I'll try to implement that feature soon but I'm quite busy at work. So be patient, please.

Well I tried out some different BLE tags, but the Giga tags and the Chipolo tags are the most reliable tags I've found yet. But I'm a little bit disappointed that the tags drain the battery even when they are not connected to another Bluetooth device. Right now I'm looking for an active device sending a code when pressing a button or something like that.

Kind Regards,
Michael

**Comment by MiGoller** [comment]
Hi Robert,

once again thx for your feedback. The adapter will reset it's connection info to offline if the Meraki API will not push data within 3 minutes after the previous received data.

Hope that will do the job for you.

Kind Regards,
Michael
